### PR TITLE
added Max's Functions

### PR DESCRIPTION
**Pull request by maxfarrell**
I added 10 functions for 10 papers, however some questions for the group arose:

1. Are we aggregating when multiple estimates per species are present?  (I did this for two databases)
2. When zip files are present, I found I needed to download the file first to a given filename, then unzip, but this doesn't look like what you have been doing so far. 
3. What are your accepted SI units for time (ex: "years", or "y")?
4. Is there a preference for augmenting variable names? (i.e. should we move to lower case?)
5. One of the datasets is included in caper, but the SI for the actual paper has the tables in PDF. Is it possible to include this, or do you need to call a dependency on caper?
6. Units for mL of O2/hour - I used mLO2/h. I didn't use a space after mL since this would imply multiplication.

### CODE REVIEW

**Comment by willpearse** [comment]
Legend, well done! Very fast, as expected :D Answering your questions in turn:

1. No - so if you could remove the aggregation, that would be helpful
2. You can use a function I wrote (`unzip`) to do that. There's a good example of that here (https://github.com/willpearse/natdb/blob/master/R/downloads.R#L463)
3. "years" is fine
4. Good question... Don't worry about it for now. I might go and lower-case everything, but that can happen in `.df.melt`. There's a bit more checking of names and things to happen before we're ready to finish that up
5. Hmmmm. Let's say include it, but could you add caper to the `DESCRIPTION` file? Just follow the format for the other packages in there.
6. I feel like that should be "mL/hour", as we wouldn't put "meters of wood" for length or something. Is this metabolic rate? If I'm doing something non-standard for the field, I guess you should go with what's standard for that field.

**Comment by willpearse** [comment]
If you just do another commit once you've handled that, then I will merge the pull request

**Comment by maxfarrell** [comment]
I changed everything mentioned in your last comment, except for one database (the Coral Traits Database - madin.2016), which still aggregates to species means. The database is already in "long" format, and has no unique identifiers per row, so some aggregation is necessary if you want to put it into the format of one trait per column (as .df.melt needs).

**Comment by willpearse** [comment]
Magic. Thanks Max, you've done a stellar job on this. I'm going to make an "issue" about the coral database, but that's not something you need to worry about. This problem has cropped up before of data already being in long format; I'll have to think of a sensible way of merging all these things together, but I don't think it'll be too hard. More soon!!!

**Pull request merged**
