### PR TITLE
update for citations

### PR DESCRIPTION
**Pull request by sylviakinosian**

### CODE REVIEW

**Comment by willpearse** [comment]
I'm a bit confused; what does this add over what we did a moment ago? Am I missing something?

**Comment by willpearse** [comment]
...I could be, because I am tired! :D

**Comment by sylviakinosian** [comment]
i just wanted to pull down the changes you just made to the citations function...

i tried "git pull" in the command line but it's saying everything is up to date, so i figured a manual pull request was needed?

**Comment by sylviakinosian** [comment]
..or is it something like `git pull willpearse/natdb`

**Comment by willpearse** [comment]
Ah - this requests *me* to pull in your changes. You're asking *me* to pull, this doesn't pull in anything for you.

Yes - you want to do something like that last one. https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by sylviakinosian** [comment]
ok thanks

**Pull request closed without merging**
