### PR TITLE
*** My First Pull Request ***

### PR DESCRIPTION
**Pull request by sylviakinosian**
not sure if you wanted to start adding functions to the main natdb repository, but i've got two (from the same paper, two datasets) that work.

### CODE REVIEW

**Comment by willpearse** [comment]
Two things (one of which I'll shout out to the group):

1. Make sure you pull in changes from the upstream branch (i.e., me) every now and again, as otherwise we get occasional conflicts that I have to manually merge. Here are some instructions: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/#platform-mac
2. Could you drop the bits in `downloads.R` that test your functions? They'll break the build process (probably)

**Comment by willpearse** [comment]
This is looking *really good*. Thank you for doing this - you've won a massive +1 for being the first person to do a pull request :D

**Comment by sylviakinosian** [comment]
okeedokee, i think i've made the changes .. but github is being a bit weird. oh well. i'll try and figure it out.

**Comment by willpearse** [comment]
Have you pushed, or is the problem with that?

Try running a pull before you push to your branch; the problem could be that I resolved some conflicts and now it's not letting you undo them...

I appreciate it might seem like I'm being a fraction pedantic, but if we figure all these things out now on a simple case, then we're doing something more complicated "on the day" then things will be "easier"...

**Comment by sylviakinosian** [comment]
It's good to figure this out now. I think it worked? I had to `pull` and then `push` again.

**Comment by willpearse** [comment]
Done! Congratulations - your first pull request! :fireworks:

**Comment by sylviakinosian** [comment]
yeehawwww

**Pull request merged**
