### PR TITLE
Function to Read Data

### PR DESCRIPTION
**Pull request by perimyotis**
Created a function to read data into NATDB from paper data located at: 10.5061/dryad.2fp34

### CODE REVIEW

**Comment by willpearse** [comment]
Thanks for this Carolyn! Could I ask for a few things from you before I accept this pull request?

- [ ] Put the code for `.peel.2016` inside `downloads.R`.
- [ ] Delete all the new files that you've added (`KamathLososEvol_AnolissagreiPerchDistAvailable.csv`, `Paul_.peel.2016.R`, and `Paul_kamath.2017d.R`)
- [ ] Only submit the function `.peel.2016`, not any calls to it or `library` (e.g., https://github.com/willpearse/natdb/pull/75/commits/94243c855cad38bba04a6bb338e9ef1fa83f44e9#diff-8520d11b83824c2a536cd9f4fe4a62b9R38)
- [ ] Copy-paste a link to the article you grabbed data from into this conversation

Thank you very much for helping with the package! You're the first to submit a pull request! Well done!

**Comment by perimyotis** [comment]
Hi Dr. Pearse, 
I think I made all of the edits you recommended correctly, if not please let me know. Also here is the article that the data is from: https://www.nature.com/articles/sdata201649

Let me know if you need anything else!

**Comment by willpearse** [comment]
Fantastic! Thanks very much!

**Comment by willpearse** [comment]
PS - Take a quick look at the change I made to the file before merging: you commented out the function definition. I sense this was a typo, but in case you are confused about how `roxygen2` works you might find it useful to look at.

Thanks again! @mrhelmus first pull request! :champagne:

**Pull request merged**
