### PR TITLE
fixed some things

### PR DESCRIPTION
**Pull request by Spencerbrucehudson**
Hey Will,

I went through my functions and found a couple that needed some modifying (column names, metadata formatting, etc).  Fixed most, but will finish the rest very soon. Created a sandbox page on the google doc spreadsheet with each function associated their creator names so folks can easily look up their taxonomy data. Went ahead and put taxonomy info there and we can remove the names afterwards. I found a handful of my functions to have several species, but can't quite remember how they were to be formatted. Currently have for example (  Animalia/Reptilia/anolis_sagrei,anolis_carolinensis,anolis_alutaceus,etc ). Do you want each species separated differently? Underscores are desired as I recall, but what about capitalizing genus? 

Can fix these sometime during the day tomorrow, but will not be able to attend the meeting in the afternoon as I'll be at an NSF workshop in Salt Lake. Hope this is alright. 

Spencer

### CODE REVIEW

**Comment by Spencerbrucehudson** [comment]
Travis failed ?! 👎

**Comment by willpearse** [comment]
More than alright! An NSF workshop sounds cool!

That formatting sounds great for the taxonomy. Don't worry about the travis fails; that predates you :D

**Comment by willpearse** [comment]
Hey - why have you removed the `.klomp.2016`? Was there a problem with that function?

**Comment by Spencerbrucehudson** [comment]
Pretty sure it was a duplicate I accidentally made. There still should be a .klomp.2016. Sorry for the confusion~

**Comment by willpearse** [comment]
Sorry to have left this one dangling for a while.

I'm a bit reticent to merge this because you've deleted so many files (e.g., the README). It also looks like this might be from an old repository that you've now deleted? If you're about at any point next week, would you mind popping by my office to talk about this? I wonder if something's just gone a bit off with it or something

**Comment by Spencerbrucehudson** [comment]
Hardly felt anything so no worries. Not sure what those changes were, however, Im confident they were crucial. Im out of town till Sunday, but will drop by early next week. And yes Im bad about deleting things..
-------- Original message --------From: Will Pearse <notifications@github.com> Date: 6/2/17  4:42 PM  (GMT-06:00) To: willpearse/natdb <natdb@noreply.github.com> Cc: Spencer Hudson <spencerbrucehudson@gmail.com>, Author <author@noreply.github.com> Subject: Re: [willpearse/natdb] fixed some things (#56) 
Sorry to have left this one dangling for a while.
I'm a bit reticent to merge this because you've deleted so many files (e.g., the README). It also looks like this might be from an old repository that you've now deleted? If you're about at any point next week, would you mind popping by my office to talk about this? I wonder if something's just gone a bit off with it or something

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/willpearse/natdb","title":"willpearse/natdb","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/willpearse/natdb"}},"updates":{"snippets":[{"icon":"PERSON","message":"@willpearse in #56: Sorry to have left this one dangling for a while.\r\n\r\nI'm a bit reticent to merge this because you've deleted so many files (e.g., the README). It also looks like this might be from an old repository that you've now deleted? If you're about at any point next week, would you mind popping by my office to talk about this? I wonder if something's just gone a bit off with it or something"}],"action":{"name":"View Pull Request","url":"https://github.com/willpearse/natdb/pull/56#issuecomment-305916167"}}}

**Comment by willpearse** [comment]
No worries. When you pop by we can figure out what you changed and make sure that gets added in. No worries!

**Pull request closed without merging**
